CREATE TABLE GamesInventory(
   ID   INT NOT NULL,
   GAMETITLE VARCHAR (30) NOT NULL,
   GAMELANGUAGE VARCHAR (30) NOT NULL,
   GAMEGENRE VARCHAR(15) NOT NULL,
   GAMECONSOLE VARCHAR(15) NOT NULL,
   GAMEMEDIUM VARCHAR(15) NOT NULL,
   GAMECONDITION VARCHAR(15) NOT NULL,
   ISLEGIT  INT NOT NULL,
   ADDRESS CHAR (25) ,
          
   PRIMARY KEY (ID)
);